#!/bin/bash

# YTC Trader - 图片提取助手
# 使用macOS自带工具从PDF提取图片

PDF_FILE="/Users/yiming/Downloads/YTC系列书籍/02 进阶篇 YTC卷二：市场和市场分析.pdf"
OUTPUT_DIR="/Users/yiming/Downloads/YTC系列书籍/ytc-trader/images/diagrams"

# 创建输出目录
mkdir -p "$OUTPUT_DIR"

echo "=== PDF图片提取助手 ==="
echo ""
echo "📖 PDF文件：$PDF_FILE"
echo "📁 输出目录：$OUTPUT_DIR"
echo ""
echo "⚠️ 注意：本脚本将使用macOS预览应用打开PDF"
echo "   请按照以下步骤操作："
echo ""
echo "📋 步骤1：打开PDF"
echo "   正在打开预览应用..."
open -a "Preview" "$PDF_FILE"
sleep 2
echo "   ✅ PDF已在预览中打开"
echo ""
echo "📋 步骤2：定位到HH+HL章节"
echo "   在预览中，使用以下方式定位："
echo "   - 点击左侧目录 → 第2章或第3章"
echo "   - 或滚动到第23-40页"
echo "   - 查找包含 'higher high' 或 'HH HL' 的图表"
echo ""
echo "📋 步骤3：提取图片"
echo "   快捷键：⌘ + ⇧ + 4 (全屏截图)"
echo "   或：⌘ + ⇧ + 5 (选择区域截图)"
echo ""
echo "📋 步骤4：保存图片"
echo "   截图后保存到桌面"
echo "   重命名为以下文件名："
echo "     - hh-hl-basic.png"
echo "     - high-point-mark.png"
echo "     - low-point-mark.png"
echo "     - trend-structure.png"
echo "   移动到：$OUTPUT_DIR"
echo ""
echo "📋 步骤5：继续提取"
echo "   滚动到下一张图表"
echo "   重复步骤3-4"
echo ""
echo "💡 提示："
echo "   - 建议提取5-8张HH+HL相关图片"
echo "   - 每张图截图后告诉我文件名"
echo "   - 我会立即更新网页显示"
echo ""
echo "✅ 准备完成！"
echo "   预览窗口应该已经打开"
echo "   请开始提取图片..."
echo ""
